export const DEFAULT_TASK_WAIT_TIMEOUT_MS = 5 * 60_000;
export const MAX_TASK_WAIT_TIMEOUT_MS = 20 * 60_000;
export const DEFAULT_TASK_WAIT_POLL_INTERVAL_MS = 1_000;
export const MAX_TASK_WAIT_POLL_INTERVAL_MS = 10_000;
export const TASK_WAIT_RPC_TIMEOUT_PADDING_MS = 5_000;
