export const DEFAULT_TASK_WATCH_TIMEOUT_MS = 60_000;
export const MAX_TASK_WATCH_TIMEOUT_MS = 20 * 60_000;
export const DEFAULT_TASK_WATCH_POLL_INTERVAL_MS = 1_000;
export const MAX_TASK_WATCH_POLL_INTERVAL_MS = 10_000;
export const TASK_WATCH_RPC_TIMEOUT_PADDING_MS = 5_000;
